version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 7000:80

  redis:
    image: redis:latest

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /home/oces/app/node_modules
      - ./server:/home/oces/app
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    privileged: true
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/oces/app/env
      - ./worker:/home/oces/app
    ports:
      - 8000:8000
      