version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000

  worker:
    privileged: true
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/env
      - ./worker:/app
    ports:
      - 8000:8000
      