name: Docker Push
on:
  push:
    branches:
      - "main"
      - "master"
      
jobs:
  Push-Containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Compilers
        uses: docker/build-push-action@v2
        with:
          context: ./compilers
          push: true
          tags: ernestwambua/oces-compilers:latest

      - name: Build and Push Nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: ernestwambua/oces-nginx:latest

      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ernestwambua/oces-server:latest

      - name: Build and push Worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: true
          tags: ernestwambua/oces-worker:latest